# Tomcat 端口配置
server:
  port: 9090


# MySQL 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dormitory?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver


# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml  # Mapper 映射文件路径
  configuration:
    map-underscore-to-camel-case: true       # 开启驼峰命名映射（数据库下划线 -> Java 驼峰）


logging:
  level:
    org.apache.ibatis: DEBUG
    com.example.springboot.mapper: DEBUG  # 替换为你的 Mapper 接口实际包路径



